### ISSUE TITLE
Without these features, I may not be able to use this very good plug-in

### ISSUE THREAD

**Issue by qingfengfenga** [clarkwinkelmann/flarum-ext-emojionearea#22]
I want to be able to manage categories separately, modify category icons, and temporarily turn off the use of certain expressions. Because in some areas, some expressions may face regulatory and copyright issues

**Comment by clarkwinkelmann** [comment]
As this is not an option offered by the EmojiOneArea library, it's not possible to add those features to this extension.

I am working on a new Flarum-native emoji picker but I can't share any timeline at this point.

If you want to restrict content, this should be done via another extension. I believe the [Filter](https://discuss.flarum.org/d/5131-friendsofflarum-filter) or [Blacklist](https://discuss.flarum.org/d/21750-post-blacklist) could help with that. There's also the now-defunkt [Decontaminator](https://discuss.flarum.org/d/23735-decontaminator-by-flarumite)
