### ISSUE TITLE
Bundled translations maintenance status

### ISSUE THREAD

**Issue by rob006** [clarkwinkelmann/flarum-ext-emojionearea#28]
What is the status of translations provided in https://github.com/clarkwinkelmann/flarum-ext-emojionearea/tree/master/locale? I'm trying to cleanup redundant translations from [Weblate](https://weblate.rob006.net/projects/flarum/) - if translation for given language is already bundled with extension, there is no sense to have it duplicated in Weblate. But this is true only for actively maintained translations, which usually means only translations maintained by extension author. For example if extension author knows Italian, he can provide `en` and `it` translations, while the rest should probably be handled inside of respective language packs. So now I'm trying to figure out which translations are available because of extension author knows this language and will be able to maintain them, and which are just leftovers from old days where translations were contributed by community to extensions instead of language packs (in that case translations may become outdated after some times, since nobody will update them).

So how does it looks like for https://github.com/clarkwinkelmann/flarum-ext-emojionearea/tree/master/locale? Which languages do you know and will be able to update if any change will be needed?

**Comment by clarkwinkelmann** [comment]
In all of my extensions I manage English and sometimes French. In this extension I accepted translations PRs in the past but I will no longer be going that for languages that aren't already added in the extension by myself.

Italian and Spanish will be removed if I ever make a feature update to this extension. But since I have not changed the translations in years I have not seen fit to remove them when they still work.

**Comment by rob006** [comment]
Thanks for the response. I removed French translations from Weblate to not duplicate work. 

As for Italian and Spanish: both are now translated on Weblate (I copied translation for Spanish, Italian was already translated), so it should be safe to remove these translations from extension in the future.

**Comment by clarkwinkelmann** [comment]
That sounds good to me :+1:
