### ISSUE TITLE
Davis' Code Review

### ISSUE THREAD

**Issue by dav-is** [clarkwinkelmann/flarum-ext-emojionearea#5]
Good work! Thought you'd appriciate some feedback. Here's what I found:

Should probably extract to separate class: https://github.com/clarkwinkelmann/flarum-ext-emojionearea/blob/master/bootstrap.php#L12

Maybe this should be a div? https://github.com/clarkwinkelmann/flarum-ext-emojionearea/blob/master/js/forum/src/components/EmojiAreaButton.js#L19

Use `const`: https://github.com/clarkwinkelmann/flarum-ext-emojionearea/blob/master/js/forum/src/components/EmojiAreaButton.js#L26

Use `const` and send texteditor as parameter: https://github.com/clarkwinkelmann/flarum-ext-emojionearea/blob/master/js/forum/src/main.js#L13

**Comment by clarkwinkelmann** [comment]
Thanks ! I think I'll do all that :+1: 

I still have to read some doc about that `const` thing because I've never actually used it :grimacing:

**Comment by dav-is** [comment]
Let me know if you need help achieving any of these or just in general :)

**Comment by clarkwinkelmann** [comment]
@dav-is I could do with some advice. I'm waiting for Gitter to come back online :see_no_evil:

**Comment by dav-is** [comment]
Which one are you having issues with?

**Comment by clarkwinkelmann** [comment]
Thanks again for your help, it's been very helpful :wink:

**Comment by dav-is** [comment]
:+1: Anytime! :)
